### ISSUE TITLE
License Should Be Added

### ISSUE THREAD

**Issue by Persistent13** [sgtoj/PSConnectWise#1]
Hello @sgtoj

I looked over the project and I could not find any indication for what license this module was released under.

I'm assuming that the module is intended to be open source and if so you can find help picking one [here](http://choosealicense.com/).

Thanks,
Dakota Clark

**Comment by sgtoj** [comment]
@Persistent13 Thank you. I will be adding a license soon. I wanted to research them before picking the one that allows it to be free with no strings attached.
