### ISSUE TITLE
Billoption cannot be set to billable (or anything other than Do Not Bill)

### ISSUE THREAD

**Issue by man0070** [sgtoj/PSConnectWise#44]
Hi all,
I have a script going utilizing the PSConnectWise module
And so far everything is going well, we have automated ticket logging and imports form CSV files - however, we are currently facing an issue with setting the billable option.
When using the integrated switch on the command: 
Add-CWTimeEntry
for instance: Add-CWTimeEntry -TicketID $ID -Start $StartTime -End $EndTime -Message $message -MemberID $MemberID -ChargeToType ServiceTicket -BillOption Billable

The bill option doesn't actually get set - and continues to revert to Do Not Bill.
I have gone through the module and replaced all references of DoNotBill (the code reference) and set to billable - this made the whole script break - which i actually found interesting.
and there were a number of other things tested as well.
i just wanted to ask - has anyone else had success setting billable options with this powershell module at all?
Assistance or pointers are appreciated!

i did a string search for all references to BillOption and replaced them with BillableOption - even manually did this (there arent too many - 2 files, Public/CWTimeEntry.ps1 and Private/PSCWApiClasses.ps1 - following this - for SOME reason - this breaks the connection function - Public/CWSession.ps1 which actually has no reference to either of these files - its so bizarre.

Any thoughts at all on this?

**Comment by man0070** [comment]
Hey Brian,

Thanks for taking a look into this,
I am just hoping to ask if you have found anything that stands out at all?

With Regards,

Rhys.

**Comment by sgtoj** [comment]
I will look in to this right now.

**Comment by sgtoj** [comment]
@man0070 Let me know if the latest update fixes it.

**Comment by man0070** [comment]
@sgtoj This has resolved the issue!
Thank you very much Brian! it is very much appreciated! thank you for look into this.
